name: repo update

on:
  push:
    paths:
      - "repo/debs/**"
      - "repo/update.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev bzip2 dos2unix

      - name: Fix line endings (Windows → Unix)
        run: dos2unix repo/update.sh

      - name: Make update.sh executable
        run: chmod +x repo/update.sh

      - name: List files (debug)
        run: ls -l

      - name: Run update script
        run: ./repo/update.sh || { echo "Update script failed"; exit 1; }

      - name: Commit updated Packages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Packages Packages.bz2
          if ! git diff --cached --quiet; then
              git commit -m "Update Packages"
              git push
          else
              echo "No changes to commit"
          fi
